config/routes.rb
Rails.application.routes.draw do
  # Rotas adicionadas pelo Devise e ActiveAdmin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  # Recursos para geração de urls
  resources :users
  resources :planned_activities,          only: [:create, :show]
  resources :performed_activities,          only: [:create, :show]
  # Path raiz direciona para a action show do controller de usuários
  root 'users#show'
  # Paths do sistema para exibição e adição das atividades
  get '/planned_activities/', to: 'planned_activities#new'
  get '/performed_activities/', to: 'performed_activities#new'
  get '/planned_activities/:id', to: 'planned_activities#show'
  get '/performed_activities/:id', to: 'performed_activities#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/performed_activity.rb
class PerformedActivity < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :text, presence: true, length: { maximum: 4096 }
end

app/models/planned_activity.rb
class PlannedActivity < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :text, presence: true, length: { maximum: 4096 }
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :team_name,    class_name: "TeamName", foreign_key: "team_name_id"
  belongs_to :user,    class_name: "User", foreign_key: "user_id"
end

app/models/team_name.rb
class TeamName < ApplicationRecord
  has_many :teams,    class_name: "Team", foreign_key: "team_name_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :planned_activities,  class_name: "PlannedActivity", foreign_key: "user_id", dependent: :destroy
  has_many :performed_activities,  class_name: "PerformedActivity", foreign_key: "user_id", dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Requer autenticação do usuário
  before_action :authenticate_user!
end

app/controllers/dm_man_controller.rb
class DmManController < ApplicationController
end

app/controllers/performed_activities_controller.rb
class PerformedActivitiesController < ApplicationController
  # Utilização da gem hashids para obfuscar os IDs das atividades dos usuários
  # fonte: https://stackoverflow.com/questions/5496935/hash-instead-of-id
  
  def new
    @performed_activity = current_user.performed_activities.build
  end

  def create
    @performed_activity = current_user.performed_activities.build(performed_activity_params)
    if @performed_activity.save
      flash[:success] = "Atividades realizadas salvas!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    id = Hashids.new("DMMan",4).decode(params[:id]).try(:first)
    @performed_activity = PerformedActivity.find(id)
  end

  def to_param
    Hashids.new("DMMan",4).encode(id)
  end

  private

    def performed_activity_params
      params.require(:performed_activity).permit(:text)
    end
end

app/controllers/planned_activities_controller.rb
class PlannedActivitiesController < ApplicationController
  # Utilização da gem hashids para obfuscar os IDs das atividades dos usuários
  # fonte: https://stackoverflow.com/questions/5496935/hash-instead-of-id

  def new
    @planned_activity = current_user.planned_activities.build
  end

  def create
    @planned_activity = current_user.planned_activities.build(planned_activity_params)
    if @planned_activity.save
      flash[:success] = "Atividades planejadas salvas!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    id = Hashids.new("DMMan",4).decode(params[:id]).try(:first)
    @planned_activity = PlannedActivity.find(id)
  end

  def to_param
    Hashids.new("DMMan",4).encode(id)
  end

  private

    def planned_activity_params
      params.require(:planned_activity).permit(:text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
       @user = User.new
  end

  def show
    @user = current_user
    @planned_activities = @user.planned_activities.page params[:page]
    @performed_activities = @user.performed_activities.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dm_man_helper.rb
module DmManHelper
end

app/helpers/performed_activities_helper.rb
module PerformedActivitiesHelper
end

app/helpers/planned_activities_helper.rb
module PlannedActivitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
- # Na página de Login, o usuário pode acessar o link da página de administração
- # Caso esteja logado, vai ver o nome cadastrado e link para sair do sistema
%header.navbar.navbar-expand-sm.bg-light.navbar-light
  .container
    %h4
      %b= link_to "DMMan", root_path, {style: "text-decoration:none", class:"text-white badge badge-pill badge-dark"}
    %nav
    - if user_signed_in?
      %ul.navbar-nav
        %span.nav-item.nav-link.nav-text
          Logado como
          %b= current_user.name
        = link_to "Sair", destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
    - else
      %ul.navbar-nav
        = link_to "Administração", admin_root_path, class: 'nav-item nav-link'

app/views/layouts/active_admin_logged_out.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale%>">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title><%= [@page_title, ActiveAdmin.application.site_title()].compact.join(" | ") %></title>

  <% ActiveAdmin.application.stylesheets.each do |style, options| %>
    <%= stylesheet_link_tag style, options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
    <%= javascript_include_tag path %>
  <% end %>

  <%= favicon_link_tag ActiveAdmin.application.favicon if ActiveAdmin.application.favicon %>

  <% ActiveAdmin.application.meta_tags_for_logged_out_pages.each do |name, content| %>
    <%= tag(:meta, name: name, content: content) %>
  <% end %>

  <%= csrf_meta_tag %>
</head>
<body class="active_admin logged_out <%= controller.action_name %>">
<div id="wrapper">

  <div id="content_wrapper">
    <% flash_messages.each do |type, message| %>
      <%= content_tag :div, message, class: "flash flash_#{type}" %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.haml
- #"Página esqueleto" que carrega o conteúdo de cada página do sistema
!!!
%html
  %head
    %title Gerenciador de Daily Meetings (DMMan)
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header'
    .container
      = yield

app/views/performed_activities/_performed_activity.html.haml
%li{id:"performed_activity-#{performed_activity.id}"}
  = link_to performed_activity.created_at, performed_activity_path(Hashids.new("DMMan",4).encode(performed_activity.id))

app/views/performed_activities/new.html.haml
- # Formulário para inserção de atividade realizada
.row
  %aside.col-md-12
    = simple_form_for(@performed_activity) do |f|
      .form-group
        = render 'shared/error_messages', object: f.object
        = f.label :text, 'O que você fez hoje? Houve algum impedimento?'
        = f.input :text, as: :text, label: false
        = f.submit "Salvar", class: "btn btn-primary"

app/views/performed_activities/show.html.haml
- # Mostra as atividades realizadas e data completa
.row
  .col-md-12
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %td Atividades realizadas
          %td Data
      %tbody
        %tr
          %td= @performed_activity.text
          %td= @performed_activity.created_at

app/views/planned_activities/_planned_activity.html.haml
%li{id:"planned_activity-#{planned_activity.id}"}
  = link_to planned_activity.created_at, planned_activity_path(Hashids.new("DMMan",4).encode(planned_activity.id))

app/views/planned_activities/new.html.haml
- # Formulário para inserção de atividade planejada
.row
  %aside.col-md-12
    = simple_form_for(@planned_activity) do |f|
      .form-group
        = render 'shared/error_messages', object: f.object
        = f.label :text, 'O que pretende fazer hoje? Há algum impedimento?'
        = f.input :text, as: :text, label: false
        = f.submit "Salvar", class: "btn btn-primary"

app/views/planned_activities/show.html.haml
- # Mostra as atividades planejadas e data completa
.row
  .col-md-12
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %td>Atividades planejadas
          %td>Data
      %tbody>
        %tr>
          %td= @planned_activity.text
          %td= @planned_activity.created_at

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = "Por favor, revise os problemas abaixo:"

app/views/users/show.html.haml
- # Página que exibe as atividades dos usuários e permite criação de novas atividades
.row
  .col-md-6
    =link_to 'Nova atividade planejada', planned_activities_url
    - if @user.planned_activities.any?
      %h6
        Atividades planejadas (
        =@user.planned_activities.count
        )
      %table.table.table-bordered.table-hover
        =paginate @planned_activities
        %thead
          %tr
            %td Data
        %tbody
          - @planned_activities.each do |pa|
            %tr
              %td= render pa
    %br
    =link_to 'Nova atividade realizada', performed_activities_url
    - if @user.planned_activities.any?
      %h6
        Atividades realizadas (
        =@user.performed_activities.count
        )
      %table.table.table-bordered.table-hover
        =paginate @performed_activities
        %thead
          %tr
            %td Data
        %tbody
          - @performed_activities.each do |pa|
            %tr
              %td= render pa